development:
  adapter: mysql2
  host: localhost
  database: myfuturegold
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  pool: 5
  database: db/test.sqlite3

production:
  adapter: mysql2
  host: localhost
  database: myfuturegold
  username: root
  password:
  pool: 5
  timeout: 5000