site_domain: staging.myfuturegold.my
google_analytics_tracker: #UA-53563177-1
s3:
  bucket: myfuturegold-staging
  region: ap-southeast-1
image_host: https://myfuturegold-staging.s3.amazonaws.com
fb_app_id: #727607077287608